# title of the software
title: The ultimate doc of Anne Berit and Aleksander

# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

baseurl: "/signering-docs"

currentVersion: "1"
versions: ["1"]

collections:
  v1:
    output: true
    permalink: /v1/

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/digipost/signering-docs
  - title: Posten signering
    url: https://signering.posten.no

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/digipost/signering-docs
  - title: Issues
    url: https://github.com/digipost/signering-docs/issues

# header
header:
  color1: "#e32d22"
  color2:
  trianglify: false

# github buttons
githubButton:
  user: digipost
  repo: signering-docs

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: digipost_no

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  trackingid: UA-77734017-1
  domain: auto

# DON'T MODIFY
highlight: rouge

github: [metadata]

plugins:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'vendor']
